### ISSUE TITLE
🗺 Epic: eth-hooks v3 initial project

### ISSUE THREAD

**Issue by ShravanSunder** [scaffold-eth/eth-hooks#50]
# Epic for v3 eth-hooks
See  scaffold-eth/scaffold-eth-typescript#23 for context

- [x] scaffold-eth/eth-hooks#25
- [x] scaffold-eth/eth-hooks#29
- [x] scaffold-eth/eth-hooks#33
- [x] scaffold-eth/eth-hooks#31
- [x] scaffold-eth/eth-hooks#35
- [x] scaffold-eth/eth-hooks#37
- [x] scaffold-eth/eth-hooks#38
- [x] scaffold-eth/eth-hooks#39
- [x] scaffold-eth/eth-hooks#47
- [x] scaffold-eth/eth-hooks#48
- [x] scaffold-eth/eth-hooks#53
